name: push-main
run-name: ${{ github.actor }} deploys on push to main
on:
  push:
    branches:
      - 'main'
      - '7-feed-list'
jobs:
  deploy_code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
