name: deploy-prod
run-name: ${{ github.actor }} deploys on push to ${{ github.ref_name }}
on:
  push:
    branches:
      - 'main'
      - '13-feed-updates-filtering'
jobs:
  deploy_code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
