name: deploy-prod
run-name: ${{ github.actor }} deploys on push to ${{ github.ref_name }}
on:
  push:
    branches:
      - 'main'
      - 'dependabot/npm_and_yarn/npm_and_yarn-6054cae836'
jobs:
  deploy_code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
